fixtures:
  repositories:
    vcsrepo: git://github.com/puppetlabs/puppetlabs-vcsrepo.git
    git: git://github.com/puppetlabs/puppetlabs-git.git
    ruby: git://github.com/puppetlabs/puppetlabs-ruby.git
    bundler: git://github.com/puppetlabs-operations/puppet-bundler.git
  symlinks:
    kibana: "#{source_dir}"
